# Generated by Django 4.2 on 2023-04-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_price_book_year'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publishinghouse',
            table='publishing_house',
        ),
    ]
