# Generated by Django 4.2 on 2023-04-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_publishinghouse_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
